site_name: AdamaJava
site_description: AdamaJava next-generation sequencing software system
site_author: Genome Informatics Group at QIMR Berghofer MRI

repo_url: https://github.com/adamajava/adamajava/

nav:
- Home: docs/index.md
- AdamaJava:
    - Introduction: docs/intro.md
    - qbamfilter: docs/qbamfilter/index.md
    - qbasepileup: docs/qbasepileup/index.md
    - qcnv: docs/qcnv/index.md
    - qcoverage: docs/qcoverage/index.md
    - qmito: docs/qmito/index.md
    - qmotif: docs/qmotif/index.md
    - qmule: qmule/index.md
    - qpileup: docs/qpileup/index.md
    - qprofiler: docs/qprofiler/index.md
    - qsignature: docs/qsignature/index.md
    - qsnp: docs/qsnp/index.md
    - qsv: docs/qsv/index.md
    - qvisualise: qvisualise/index.md

theme:
    name: readthedocs
    collapse_navigation: true
    titles_only: false
    sticky_navigation: true
