package au.edu.qimr.clinvar.model;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class BinTest {
	
	@Test
	public void areTheseBinsReallyEqual() {
		Bin b1 = new Bin(1, "TTTTAAGTATGATGAAGTCACCTGAATGAATACAGCCAAAATATGAACAACCTCTACTATATTACACAAACTTTTAGCGCCTAGCAATAGGGTGCCTCTTAAACCCAATACACAGCTTTGAATTGAAATGAAAACTTACTTGCAGTTCTGGCACACTTTGCACTCAGGACATTGCCAACCTGCACGTTTTAATGGAGTAACCGCTATATCCAGGCACATTCCATGATAGTGCTGACCACAAG", 1);
		Bin b2 = new Bin(2, "TTTTAAGTATGATGAAGTCACCTGAATGAATACAGCCAAAATATGAACAACCTCTATTATATTACACAAACTTTTAGCGCCTAGCAATAGGGTGCCTCTAAAACCCAATACACAGCTTTGAATTGAAATGAAAACTTACTTGCAGTTCTGGCACACTTTGCACTCAGGACATTGCCAACCTGCACGTTTTAAAGGAGTAACCGCTATATCCAGGCACATTCCATGATAGTGCTGACCACAAG", 2);
		assertEquals(false, b1.equals(b2));
	}

}
