package au.edu.qimr.clinvar.model;

import static org.junit.Assert.assertEquals;
import net.sf.samtools.util.SequenceUtil;

import org.junit.Test;

public class ProbeTest {
	
	@Test
	public void getSequenceProbe7() {
		//public Probe(int id, String dlsoSeq, String dlsoSeqRC, String ulsoSeq, String ulsoSeqRC, int p1Start, int p1End, int p2Start, int p2End, String subseq, int ssStart, int ssEnd, String chr) {
		String subseq = "GGTTCACGCCATTCTCCTGCCTCAGCCTCCTGAGTAGCTGGGACTACAGGCACCTGCCACCAGGCCCAGCTACTTTTTTGTATTTTTAGTAGAGATGGGGTTTCACCGTGTTAGCCAGGATGGTCTCGATCTGCTGACCTCCTGATCCACCCGCTTCGGCCTCCCAAAGTGCTGGGATTACGGGCGTGCGCCACTGCACCTGGCGACCTTGTAATTCTTTATGTTTTCCAGTTTTCTTCCTTTGTCTCCCTCTTCCCTCAGCTTCAGCTTTGTAAATGCTTTTGAGTCTTTGAGGGGAATAGTTAAATGAATTGCTTAGTGTTCTCTTTATGGAAGTAGCCATTAAGTTTTTTGTTGTTTGTTTTTATGATAATGATGACTTCCTATTACTTCCATTCTGACGCTAGACATGGATTCCTCTAGGAATATACTGGCATTTTGGCTGTCTACCCAGCTGTTGCTTCCATTTGCCTATTCCTTGAGTGTAAGGCAATTAATAACTTACACTTGTCTTTATGTTCCAGCCTGAAAGAATAGACCCAAGCGCATCACGACAAGGATATGATGTCCGCTCTGATGTCTGGAGTTTGGGGATCACATTGGTATGTTTATGCTGATTCAACCTTGCCACAGTAGCGTAACAATAAGAAATTTAGAAGTGAAAGAAAACTTAATCAGACTTCCCCGTTCGTTAAGAACTATAATCACAGACACTATGGTTTTAAGTTGCTGAAAAAAAAAAAGTATGTATTTATTTACTTTAAAAATCAAATCAGACTTGATTATTTCCCTTGAAGTTATGTGAAGTGTCTAGAGCCCTTTAATGTTTTAACTGGATCTCTTGGCCACAGATAATAGGAGTCAACTATTATCTGCAACTGCACTAAGAATGGGAACAGGACAAGCCAGCTTACCTGCAGTCAATTCATTGATGAAGGCACATAGGCTTCTCCCATCTCAGGCAAGGTGTAGTATGTCCAGTAATACTGTATATAGTGTGTATATTAAGTATACGTATTTTTATATGTGGAAAATAGTTTCTACTTGCAATATTCTATTCACTGAATAGTAAAATCACAAGTGAATGAGCTGAAAGTAATTCAGTTTTTGAGGGACAATATATTAGT";
		Probe p = new Probe(7, "AATTGCCTTACACTCAAGGAATAGG", "CCTATTCCTTGAGTGTAAGGCAATT", "GTTCTTAACGAACGGGGAAGTCTGATT", "AATCAGACTTCCCCGTTCGTTAAGAAC",
				12028556, 12028580, 12028758, 12028784, subseq, 12028086, 12029213, "chr17", false);
		
		String probeRef = p.getReferenceSequence();
		System.out.println("p7 ref: " + probeRef);
		assertEquals(p.getExpectedFragmentLength(), probeRef.length());
		
		String bin = "CCTATTCCTTGAGTGTAAGGCAATTAATAACTTACACTTGTCTTTATGTTCCAGCCTGAAAGAATAGACCCAAGCGCATCACGACAAGGATATGATGTCCGCTCTGATGTCTGGAGTTTGGGGATCACATTGGTATGTTTATGCTGATTCAACCTTGCCACAGTAGCGTAACAATAAGAAATTTAGAAGTGAAAGAAAACTTAATCAGACTTCCCCGTTCGTTAAGAAC";
		// need to RC bin as we are on the reverse strand
		
		assertEquals(probeRef, bin);
//		assertEquals(probeRef, SequenceUtil.reverseComplement(bin));
	}
	@Test
	public void getSequenceProbe12() {
		//public Probe(int id, String dlsoSeq, String dlsoSeqRC, String ulsoSeq, String ulsoSeqRC, int p1Start, int p1End, int p2Start, int p2End, String subseq, int ssStart, int ssEnd, String chr) {
		String subseq = "ATACCTGGGCATTGAGATTTTTAAAATCTCCCCCAGGTGATTGTAAGGTACAGCAAACCTTGGGAATAGTTGTACTAACTGAAGATTGAGGCACTGGAATAACTAATGTTGGGTAAGATAGGGTAAGAACTTTTTCGCAATAAGGTTTGCAGCTCTTGGGATTCTCACTTGATAATGCTGTTTGGATAAACCATCATCCAAGTTTGAATAAGATCTTATATTTAGAAATGAAAACTGATCTGCAGAATTAGTTTAATCAATAAATGGGAATTTTTAAAAATCTTCTTGGCAATTTGTTTTTATGAATCCCGTTGAAGCTGTGTCTATTGACTACCTAAATCTAGATCATTCTTAATCCAGTGTGTAAAAAACCAGGATGACACAAATGAAAAACTTCAAAAACCTGGAGGTCAGACTATTTTAGTAATTTAGAAAACATTTTTCCCACACATTAATCAGTACTAAAAGAAAAAAGTTAAAACCTATTTAAAATGTGGAAAAATTGCTTCCCAATATTTTAACAGAGAGAGACTGAGAACACACAGCATTGAGTCATCAGGAAAACTGAAGATCTCCCCTGAACAACACTGGGATTTCACTGCAGAGGACTTGAAAGACCTTGGAGAAATTGGACGAGGAGCTTATGGTTCTGTCAACAAAATGGTCCACAAACCAAGTGGGCAAATAATGGCAGTTAAAGTAGGTGATGCCATGATTATTTTTGGTACTTTAATCCATTAGGTGAAATTTCATGGTGCAGTAATACCACTGTTGTTGTGTTCCTACTTTTGTGGTAAATGTGGGTGTTTAAAAAATTGTTTCTCCAACTCCTTTGAGGGTGTTCTGTGTAGAGGTTTCTTATTGGTGGCACATTTTCTATCTCTTTGGAAACATGAGTGTATGAAGTGTGCATGTTGATTGCATTTTTGGCATGATGCATTAACATGTTTTAAACTTCAGGCCCTTCTACTGCCAAGGTGAGTTCAGGCTGGGCGGCTGCACCCCTGGGAGCAGGGCAGTGCTGCACTGAGCCAGGCGGGAGCTGGAAGAAGACGCAGCACACTGGGTTGGGCAAGGTGCGGGGCTAGGGCTAACAGCAGTCTTACTGAAGGTTTCCTGGAAACCACGCACATGCTGTTGCCACTAACCTCAACCTTACTCGGTCCTGACCGGCTCGGCTTCTGTTTGTTTATTTCATCTCTACTCAGTACTGCCCTGTTCCCT";
		Probe p = new Probe(12, "TGAAATTTCATGGTGCAGTAATACCACTG", "CAGTGGTATTACTGCACCATGAAATTTCA", "GCATTGAGTCATCAGGAAAACTGAAGA", "TCTTCAGTTTTCCTGATGACTCAATGC",
				11984692, 11984718, 11984890, 11984918, subseq, 11984148, 11985372, "chr17", true);
		
		String probeRef = p.getReferenceSequence();
		System.out.println("p12 ref: " + probeRef);
		assertEquals(p.getExpectedFragmentLength(), probeRef.length());
		
		String bin = "CAGTGGTATTACTGCACCATGAAATTTCACCTAATGGATTAAAGTACCAAAAATAATCATGGCATCACCTACTTTAACTGCCATTATTTGCCCACTTGGTTTGTGGACCATTTTGTTGACAGAACCATAAGCTCCTCGTCCAATTTCTCCAAGGTCTTTCAAGTCCTCTGCAGTGAAATCCCAGTGTTGTTCAGGGGAGATCTTCAGTTTTCCTGATGACTCAATGC";
		bin = SequenceUtil.reverseComplement(bin);
		System.out.println("p12 bin: " + bin);
		
		// is bin in subseq
		assertEquals(true, subseq.contains(bin));
		assertEquals(probeRef, bin);
	}

}
