/**
 * © Copyright The University of Queensland 2010-2014.  This code is released under the terms outlined in the included LICENSE file.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 10:52:21 AM EST 
//


package org.qcmg.dbsnp;



public class Dbsnp130Record {

    protected String refSnp;
    protected String chromosome;
    protected int chromosomePosition;
    protected String strand;
    protected String refGenome;
    protected String variant;

    /**
     * Gets the value of the refSnp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefSnp() {
        return refSnp;
    }

    /**
     * Sets the value of the refSnp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefSnp(String value) {
        this.refSnp = value;
    }

    /**
     * Gets the value of the chromosome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChromosome() {
        return chromosome;
    }

    /**
     * Sets the value of the chromosome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChromosome(String value) {
        this.chromosome = value;
    }

    /**
     * Gets the value of the chromosomePosition property.
     * 
     */
    public int getChromosomePosition() {
        return chromosomePosition;
    }

    /**
     * Sets the value of the chromosomePosition property.
     * 
     */
    public void setChromosomePosition(int value) {
        this.chromosomePosition = value;
    }

    /**
     * Gets the value of the strand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrand() {
        return strand;
    }

    /**
     * Sets the value of the strand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrand(String value) {
        this.strand = value;
    }

    /**
     * Gets the value of the refGenome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefGenome() {
        return refGenome;
    }

    /**
     * Sets the value of the refGenome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefGenome(String value) {
        this.refGenome = value;
    }

    /**
     * Gets the value of the variant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariant() {
        return variant;
    }

    /**
     * Sets the value of the variant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariant(String value) {
        this.variant = value;
    }

}
