/**
 * © Copyright The University of Queensland 2010-2014.  This code is released under the terms outlined in the included LICENSE file.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.05 at 09:43:33 AM EST 
//


package org.qcmg.qbamannotate;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.qcmg.qbamannotate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.qcmg.qbamannotate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LongMatePairReport.UniquePairing }
     * 
     */
    public LongMatePairReport.UniquePairing createLongMatePairReportUniquePairing() {
        return new LongMatePairReport.UniquePairing();
    }

    /**
     * Create an instance of {@link FragBarCodeReport }
     * 
     */
    public FragBarCodeReport createFragBarCodeReport() {
        return new FragBarCodeReport();
    }

    /**
     * Create an instance of {@link PairedEndReport.InsertRange }
     * 
     */
    public PairedEndReport.InsertRange createPairedEndReportInsertRange() {
        return new PairedEndReport.InsertRange();
    }

    /**
     * Create an instance of {@link FragReport.UniquePairing }
     * 
     */
    public FragReport.UniquePairing createFragReportUniquePairing() {
        return new FragReport.UniquePairing();
    }

    /**
     * Create an instance of {@link PairedEndReport.UniquePairing }
     * 
     */
    public PairedEndReport.UniquePairing createPairedEndReportUniquePairing() {
        return new PairedEndReport.UniquePairing();
    }

    /**
     * Create an instance of {@link PairedEndReport }
     * 
     */
    public PairedEndReport createPairedEndReport() {
        return new PairedEndReport();
    }

    /**
     * Create an instance of {@link LongMatePairReport.InsertRange }
     * 
     */
    public LongMatePairReport.InsertRange createLongMatePairReportInsertRange() {
        return new LongMatePairReport.InsertRange();
    }

    /**
     * Create an instance of {@link LongMatePairReport }
     * 
     */
    public LongMatePairReport createLongMatePairReport() {
        return new LongMatePairReport();
    }

    /**
     * Create an instance of {@link FragBarCodeReport.Pairing }
     * 
     */
    public FragBarCodeReport.Pairing createFragBarCodeReportPairing() {
        return new FragBarCodeReport.Pairing();
    }

    /**
     * Create an instance of {@link FragReport }
     * 
     */
    public FragReport createFragReport() {
        return new FragReport();
    }

}
