//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 10:52:22 AM EST 
//


package org.qcmg.primeroutput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for primerOutputHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="primerOutputHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sequenceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sequenceTemplate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sequenceTarget" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productMinTm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="productMaxTm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dnaConc" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="saltConc" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="minTm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="optTm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxTm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="minSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="optSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="productSizeRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="explainFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="numReturn" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numNsAccepted" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="leftExplain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rightExplain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pairExplain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="leftNumReturned" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rightNumReturned" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="internalNumReturned" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pairNumReturned" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "primerOutputHeader", propOrder = {
    "sequenceId",
    "sequenceTemplate",
    "sequenceTarget",
    "productMinTm",
    "productMaxTm",
    "dnaConc",
    "saltConc",
    "minTm",
    "optTm",
    "maxTm",
    "minSize",
    "optSize",
    "maxSize",
    "productSizeRange",
    "explainFlag",
    "numReturn",
    "numNsAccepted",
    "leftExplain",
    "rightExplain",
    "pairExplain",
    "leftNumReturned",
    "rightNumReturned",
    "internalNumReturned",
    "pairNumReturned"
})
public class PrimerOutputHeader {

    @XmlElement(required = true)
    protected String sequenceId;
    @XmlElement(required = true)
    protected String sequenceTemplate;
    @XmlElement(required = true)
    protected String sequenceTarget;
    protected int productMinTm;
    protected int productMaxTm;
    protected double dnaConc;
    protected double saltConc;
    protected int minTm;
    protected int optTm;
    protected int maxTm;
    protected int minSize;
    protected int optSize;
    protected int maxSize;
    @XmlElement(required = true)
    protected String productSizeRange;
    protected boolean explainFlag;
    protected int numReturn;
    protected int numNsAccepted;
    @XmlElement(required = true)
    protected String leftExplain;
    @XmlElement(required = true)
    protected String rightExplain;
    @XmlElement(required = true)
    protected String pairExplain;
    protected int leftNumReturned;
    protected int rightNumReturned;
    protected int internalNumReturned;
    protected int pairNumReturned;

    /**
     * Gets the value of the sequenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceId() {
        return sequenceId;
    }

    /**
     * Sets the value of the sequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceId(String value) {
        this.sequenceId = value;
    }

    /**
     * Gets the value of the sequenceTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceTemplate() {
        return sequenceTemplate;
    }

    /**
     * Sets the value of the sequenceTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceTemplate(String value) {
        this.sequenceTemplate = value;
    }

    /**
     * Gets the value of the sequenceTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceTarget() {
        return sequenceTarget;
    }

    /**
     * Sets the value of the sequenceTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceTarget(String value) {
        this.sequenceTarget = value;
    }

    /**
     * Gets the value of the productMinTm property.
     * 
     */
    public int getProductMinTm() {
        return productMinTm;
    }

    /**
     * Sets the value of the productMinTm property.
     * 
     */
    public void setProductMinTm(int value) {
        this.productMinTm = value;
    }

    /**
     * Gets the value of the productMaxTm property.
     * 
     */
    public int getProductMaxTm() {
        return productMaxTm;
    }

    /**
     * Sets the value of the productMaxTm property.
     * 
     */
    public void setProductMaxTm(int value) {
        this.productMaxTm = value;
    }

    /**
     * Gets the value of the dnaConc property.
     * 
     */
    public double getDnaConc() {
        return dnaConc;
    }

    /**
     * Sets the value of the dnaConc property.
     * 
     */
    public void setDnaConc(double value) {
        this.dnaConc = value;
    }

    /**
     * Gets the value of the saltConc property.
     * 
     */
    public double getSaltConc() {
        return saltConc;
    }

    /**
     * Sets the value of the saltConc property.
     * 
     */
    public void setSaltConc(double value) {
        this.saltConc = value;
    }

    /**
     * Gets the value of the minTm property.
     * 
     */
    public int getMinTm() {
        return minTm;
    }

    /**
     * Sets the value of the minTm property.
     * 
     */
    public void setMinTm(int value) {
        this.minTm = value;
    }

    /**
     * Gets the value of the optTm property.
     * 
     */
    public int getOptTm() {
        return optTm;
    }

    /**
     * Sets the value of the optTm property.
     * 
     */
    public void setOptTm(int value) {
        this.optTm = value;
    }

    /**
     * Gets the value of the maxTm property.
     * 
     */
    public int getMaxTm() {
        return maxTm;
    }

    /**
     * Sets the value of the maxTm property.
     * 
     */
    public void setMaxTm(int value) {
        this.maxTm = value;
    }

    /**
     * Gets the value of the minSize property.
     * 
     */
    public int getMinSize() {
        return minSize;
    }

    /**
     * Sets the value of the minSize property.
     * 
     */
    public void setMinSize(int value) {
        this.minSize = value;
    }

    /**
     * Gets the value of the optSize property.
     * 
     */
    public int getOptSize() {
        return optSize;
    }

    /**
     * Sets the value of the optSize property.
     * 
     */
    public void setOptSize(int value) {
        this.optSize = value;
    }

    /**
     * Gets the value of the maxSize property.
     * 
     */
    public int getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     * 
     */
    public void setMaxSize(int value) {
        this.maxSize = value;
    }

    /**
     * Gets the value of the productSizeRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductSizeRange() {
        return productSizeRange;
    }

    /**
     * Sets the value of the productSizeRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSizeRange(String value) {
        this.productSizeRange = value;
    }

    /**
     * Gets the value of the explainFlag property.
     * 
     */
    public boolean isExplainFlag() {
        return explainFlag;
    }

    /**
     * Sets the value of the explainFlag property.
     * 
     */
    public void setExplainFlag(boolean value) {
        this.explainFlag = value;
    }

    /**
     * Gets the value of the numReturn property.
     * 
     */
    public int getNumReturn() {
        return numReturn;
    }

    /**
     * Sets the value of the numReturn property.
     * 
     */
    public void setNumReturn(int value) {
        this.numReturn = value;
    }

    /**
     * Gets the value of the numNsAccepted property.
     * 
     */
    public int getNumNsAccepted() {
        return numNsAccepted;
    }

    /**
     * Sets the value of the numNsAccepted property.
     * 
     */
    public void setNumNsAccepted(int value) {
        this.numNsAccepted = value;
    }

    /**
     * Gets the value of the leftExplain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeftExplain() {
        return leftExplain;
    }

    /**
     * Sets the value of the leftExplain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeftExplain(String value) {
        this.leftExplain = value;
    }

    /**
     * Gets the value of the rightExplain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightExplain() {
        return rightExplain;
    }

    /**
     * Sets the value of the rightExplain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightExplain(String value) {
        this.rightExplain = value;
    }

    /**
     * Gets the value of the pairExplain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPairExplain() {
        return pairExplain;
    }

    /**
     * Sets the value of the pairExplain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPairExplain(String value) {
        this.pairExplain = value;
    }

    /**
     * Gets the value of the leftNumReturned property.
     * 
     */
    public int getLeftNumReturned() {
        return leftNumReturned;
    }

    /**
     * Sets the value of the leftNumReturned property.
     * 
     */
    public void setLeftNumReturned(int value) {
        this.leftNumReturned = value;
    }

    /**
     * Gets the value of the rightNumReturned property.
     * 
     */
    public int getRightNumReturned() {
        return rightNumReturned;
    }

    /**
     * Sets the value of the rightNumReturned property.
     * 
     */
    public void setRightNumReturned(int value) {
        this.rightNumReturned = value;
    }

    /**
     * Gets the value of the internalNumReturned property.
     * 
     */
    public int getInternalNumReturned() {
        return internalNumReturned;
    }

    /**
     * Sets the value of the internalNumReturned property.
     * 
     */
    public void setInternalNumReturned(int value) {
        this.internalNumReturned = value;
    }

    /**
     * Gets the value of the pairNumReturned property.
     * 
     */
    public int getPairNumReturned() {
        return pairNumReturned;
    }

    /**
     * Sets the value of the pairNumReturned property.
     * 
     */
    public void setPairNumReturned(int value) {
        this.pairNumReturned = value;
    }

}
