#qbamannotate_paired_single_ma.pbs

#These commands set up the Grid Environment for your job:
#PBS -N qbamannotate_paired_single_ma
#PBS -l nodes=1,walltime=6:00:00,ncpus=2
#PBS -S /bin/bash
#PBS -d /path/testbed/

export ADAMA_HOME=/path/testbed/local/adama/
export PATH=$ADAMA_HOME/bin:$PATH

inputDir=/path/S0014_20090108_1_MC58/20100609

inputBAM=$inputDir/pairing/F3-R3-Paired.bam
firstMA=$inputDir/F3/s_mapping/S0014_20090108_1_MC58_MC58_F3.csfasta.ma

outputDir=/path/testbed/
sortedInputBAM=$outputDir/sorted_paired_single_ma
outputBAM=$outputDir/qbamannotated_paired_single_ma.bam

# Actual processing
qbamannotate $outputBAM $sortedInputBAM.bam $firstMA
