/**
 * © Copyright The University of Queensland 2010-2014.  This code is released under the terms outlined in the included LICENSE file.
 */
package org.qcmg.ensembl.model;


// default package
// Generated May 9, 2011 1:21:58 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * GeneStableId generated by hbm2java
 */
@Entity
@Table(name = "homo_sapiens_core_55_37.gene_stable_id")
public class GeneStableId implements java.io.Serializable {

	private static final long serialVersionUID = 3504256468754175683L;
	
	private Gene gene;
	private Integer version;
	private String stableId;
	private Date createdDate;
	private Date modifiedDate;

	public GeneStableId() {
	}

	public GeneStableId(Gene gene, String stableId, Date createdDate,
			Date modifiedDate) {
		this.gene = gene;
		this.stableId = stableId;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@ManyToOne
	@JoinColumn(name = "gene_id", unique = true, nullable = false)
	public Gene getGene() {
		return this.gene;
	}

	public void setGene(Gene gene) {
		this.gene = gene;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "stable_id", nullable = false, length = 128)
	public String getStableId() {
		return this.stableId;
	}

	public void setStableId(String stableId) {
		this.stableId = stableId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", nullable = false, length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
